//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP.ServiceParticipante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciosWeb/", ConfigurationName="ServiceParticipante.ServicioWebParticipante")]
    public interface ServicioWebParticipante {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/EstadisticasRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/EstadisticasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.EstadisticasResponse Estadisticas(ClienteSOAP.ServiceParticipante.EstadisticasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/EstadisticasRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/EstadisticasResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.EstadisticasResponse> EstadisticasAsync(ClienteSOAP.ServiceParticipante.EstadisticasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/listarPartidosDeUnParticipanteRequest" +
            "", ReplyAction="http://serviciosWeb/ServicioWebParticipante/listarPartidosDeUnParticipanteRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse listarPartidosDeUnParticipante(ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/listarPartidosDeUnParticipanteRequest" +
            "", ReplyAction="http://serviciosWeb/ServicioWebParticipante/listarPartidosDeUnParticipanteRespons" +
            "e")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse> listarPartidosDeUnParticipanteAsync(ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/eliminarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/eliminarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse eliminarParticipante(ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/eliminarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/eliminarParticipanteResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse> eliminarParticipanteAsync(ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/actualizarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/actualizarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse actualizarParticipante(ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/actualizarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/actualizarParticipanteResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse> actualizarParticipanteAsync(ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/listarParticipantesRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/listarParticipantesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.listarParticipantesResponse listarParticipantes(ClienteSOAP.ServiceParticipante.listarParticipantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/listarParticipantesRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/listarParticipantesResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarParticipantesResponse> listarParticipantesAsync(ClienteSOAP.ServiceParticipante.listarParticipantesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/filtrarParticipantePorApodoRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/filtrarParticipantePorApodoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse filtrarParticipantePorApodo(ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/filtrarParticipantePorApodoRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/filtrarParticipantePorApodoResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse> filtrarParticipantePorApodoAsync(ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/buscarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/buscarParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.buscarParticipanteResponse buscarParticipante(ClienteSOAP.ServiceParticipante.buscarParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/buscarParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/buscarParticipanteResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.buscarParticipanteResponse> buscarParticipanteAsync(ClienteSOAP.ServiceParticipante.buscarParticipanteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/crearParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/crearParticipanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAP.ServiceParticipante.crearParticipanteResponse crearParticipante(ClienteSOAP.ServiceParticipante.crearParticipanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciosWeb/ServicioWebParticipante/crearParticipanteRequest", ReplyAction="http://serviciosWeb/ServicioWebParticipante/crearParticipanteResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.crearParticipanteResponse> crearParticipanteAsync(ClienteSOAP.ServiceParticipante.crearParticipanteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class participante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apodoField;
        
        private System.DateTime fecha_caducidadField;
        
        private bool fecha_caducidadFieldSpecified;
        
        private System.DateTime fecha_inscripcionField;
        
        private bool fecha_inscripcionFieldSpecified;
        
        private int idField;
        
        private partido[] partidoListField;
        
        private partido[] partidoList1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                this.apodoField = value;
                this.RaisePropertyChanged("apodo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha_caducidad {
            get {
                return this.fecha_caducidadField;
            }
            set {
                this.fecha_caducidadField = value;
                this.RaisePropertyChanged("fecha_caducidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_caducidadSpecified {
            get {
                return this.fecha_caducidadFieldSpecified;
            }
            set {
                this.fecha_caducidadFieldSpecified = value;
                this.RaisePropertyChanged("fecha_caducidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_inscripcion {
            get {
                return this.fecha_inscripcionField;
            }
            set {
                this.fecha_inscripcionField = value;
                this.RaisePropertyChanged("fecha_inscripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_inscripcionSpecified {
            get {
                return this.fecha_inscripcionFieldSpecified;
            }
            set {
                this.fecha_inscripcionFieldSpecified = value;
                this.RaisePropertyChanged("fecha_inscripcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partidoList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public partido[] partidoList {
            get {
                return this.partidoListField;
            }
            set {
                this.partidoListField = value;
                this.RaisePropertyChanged("partidoList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partidoList1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public partido[] partidoList1 {
            get {
                return this.partidoList1Field;
            }
            set {
                this.partidoList1Field = value;
                this.RaisePropertyChanged("partidoList1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class partido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fecha_programadaField;
        
        private bool fecha_programadaFieldSpecified;
        
        private int ganadorField;
        
        private System.DateTime hora_finField;
        
        private bool hora_finFieldSpecified;
        
        private System.DateTime hora_inicioField;
        
        private bool hora_inicioFieldSpecified;
        
        private mesa mesaField;
        
        private participante participanteField;
        
        private participante participante1Field;
        
        private int rondaField;
        
        private string torneoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha_programada {
            get {
                return this.fecha_programadaField;
            }
            set {
                this.fecha_programadaField = value;
                this.RaisePropertyChanged("fecha_programada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_programadaSpecified {
            get {
                return this.fecha_programadaFieldSpecified;
            }
            set {
                this.fecha_programadaFieldSpecified = value;
                this.RaisePropertyChanged("fecha_programadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ganador {
            get {
                return this.ganadorField;
            }
            set {
                this.ganadorField = value;
                this.RaisePropertyChanged("ganador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime hora_fin {
            get {
                return this.hora_finField;
            }
            set {
                this.hora_finField = value;
                this.RaisePropertyChanged("hora_fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hora_finSpecified {
            get {
                return this.hora_finFieldSpecified;
            }
            set {
                this.hora_finFieldSpecified = value;
                this.RaisePropertyChanged("hora_finSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime hora_inicio {
            get {
                return this.hora_inicioField;
            }
            set {
                this.hora_inicioField = value;
                this.RaisePropertyChanged("hora_inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hora_inicioSpecified {
            get {
                return this.hora_inicioFieldSpecified;
            }
            set {
                this.hora_inicioFieldSpecified = value;
                this.RaisePropertyChanged("hora_inicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public mesa mesa {
            get {
                return this.mesaField;
            }
            set {
                this.mesaField = value;
                this.RaisePropertyChanged("mesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public participante participante {
            get {
                return this.participanteField;
            }
            set {
                this.participanteField = value;
                this.RaisePropertyChanged("participante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public participante participante1 {
            get {
                return this.participante1Field;
            }
            set {
                this.participante1Field = value;
                this.RaisePropertyChanged("participante1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int ronda {
            get {
                return this.rondaField;
            }
            set {
                this.rondaField = value;
                this.RaisePropertyChanged("ronda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string torneo {
            get {
                return this.torneoField;
            }
            set {
                this.torneoField = value;
                this.RaisePropertyChanged("torneo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serviciosWeb/")]
    public partial class mesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_mesaField;
        
        private string localidadField;
        
        private string nombre_lugarField;
        
        private partido[] partidoList2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_mesa {
            get {
                return this.id_mesaField;
            }
            set {
                this.id_mesaField = value;
                this.RaisePropertyChanged("id_mesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
                this.RaisePropertyChanged("localidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre_lugar {
            get {
                return this.nombre_lugarField;
            }
            set {
                this.nombre_lugarField = value;
                this.RaisePropertyChanged("nombre_lugar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("partidoList2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public partido[] partidoList2 {
            get {
                return this.partidoList2Field;
            }
            set {
                this.partidoList2Field = value;
                this.RaisePropertyChanged("partidoList2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Estadisticas", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class EstadisticasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public EstadisticasRequest() {
        }
        
        public EstadisticasRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EstadisticasResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class EstadisticasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] @return;
        
        public EstadisticasResponse() {
        }
        
        public EstadisticasResponse(System.Nullable<int>[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidosDeUnParticipante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarPartidosDeUnParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public listarPartidosDeUnParticipanteRequest() {
        }
        
        public listarPartidosDeUnParticipanteRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPartidosDeUnParticipanteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarPartidosDeUnParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.partido[] @return;
        
        public listarPartidosDeUnParticipanteResponse() {
        }
        
        public listarPartidosDeUnParticipanteResponse(ClienteSOAP.ServiceParticipante.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarParticipante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public eliminarParticipanteRequest() {
        }
        
        public eliminarParticipanteRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarParticipanteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class eliminarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarParticipanteResponse() {
        }
        
        public eliminarParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarParticipante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public actualizarParticipanteRequest() {
        }
        
        public actualizarParticipanteRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarParticipanteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class actualizarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarParticipanteResponse() {
        }
        
        public actualizarParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantes", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarParticipantesRequest {
        
        public listarParticipantesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarParticipantesResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class listarParticipantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante[] @return;
        
        public listarParticipantesResponse() {
        }
        
        public listarParticipantesResponse(ClienteSOAP.ServiceParticipante.participante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarParticipantePorApodo", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class filtrarParticipantePorApodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public filtrarParticipantePorApodoRequest() {
        }
        
        public filtrarParticipantePorApodoRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="filtrarParticipantePorApodoResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class filtrarParticipantePorApodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante[] @return;
        
        public filtrarParticipantePorApodoResponse() {
        }
        
        public filtrarParticipantePorApodoResponse(ClienteSOAP.ServiceParticipante.participante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarParticipante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public buscarParticipanteRequest() {
        }
        
        public buscarParticipanteRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarParticipanteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class buscarParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante @return;
        
        public buscarParticipanteResponse() {
        }
        
        public buscarParticipanteResponse(ClienteSOAP.ServiceParticipante.participante @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearParticipante", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class crearParticipanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSOAP.ServiceParticipante.participante arg0;
        
        public crearParticipanteRequest() {
        }
        
        public crearParticipanteRequest(ClienteSOAP.ServiceParticipante.participante arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearParticipanteResponse", WrapperNamespace="http://serviciosWeb/", IsWrapped=true)]
    public partial class crearParticipanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serviciosWeb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public crearParticipanteResponse() {
        }
        
        public crearParticipanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebParticipanteChannel : ClienteSOAP.ServiceParticipante.ServicioWebParticipante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebParticipanteClient : System.ServiceModel.ClientBase<ClienteSOAP.ServiceParticipante.ServicioWebParticipante>, ClienteSOAP.ServiceParticipante.ServicioWebParticipante {
        
        public ServicioWebParticipanteClient() {
        }
        
        public ServicioWebParticipanteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebParticipanteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebParticipanteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebParticipanteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.EstadisticasResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.Estadisticas(ClienteSOAP.ServiceParticipante.EstadisticasRequest request) {
            return base.Channel.Estadisticas(request);
        }
        
        public System.Nullable<int>[] Estadisticas(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.EstadisticasRequest inValue = new ClienteSOAP.ServiceParticipante.EstadisticasRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.EstadisticasResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).Estadisticas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.EstadisticasResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.EstadisticasAsync(ClienteSOAP.ServiceParticipante.EstadisticasRequest request) {
            return base.Channel.EstadisticasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.EstadisticasResponse> EstadisticasAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.EstadisticasRequest inValue = new ClienteSOAP.ServiceParticipante.EstadisticasRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).EstadisticasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.listarPartidosDeUnParticipante(ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest request) {
            return base.Channel.listarPartidosDeUnParticipante(request);
        }
        
        public ClienteSOAP.ServiceParticipante.partido[] listarPartidosDeUnParticipante(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).listarPartidosDeUnParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.listarPartidosDeUnParticipanteAsync(ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest request) {
            return base.Channel.listarPartidosDeUnParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteResponse> listarPartidosDeUnParticipanteAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.listarPartidosDeUnParticipanteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).listarPartidosDeUnParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.eliminarParticipante(ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest request) {
            return base.Channel.eliminarParticipante(request);
        }
        
        public int eliminarParticipante(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).eliminarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.eliminarParticipanteAsync(ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest request) {
            return base.Channel.eliminarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.eliminarParticipanteResponse> eliminarParticipanteAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.eliminarParticipanteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).eliminarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.actualizarParticipante(ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest request) {
            return base.Channel.actualizarParticipante(request);
        }
        
        public int actualizarParticipante(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).actualizarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.actualizarParticipanteAsync(ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest request) {
            return base.Channel.actualizarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.actualizarParticipanteResponse> actualizarParticipanteAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.actualizarParticipanteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).actualizarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.listarParticipantesResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.listarParticipantes(ClienteSOAP.ServiceParticipante.listarParticipantesRequest request) {
            return base.Channel.listarParticipantes(request);
        }
        
        public ClienteSOAP.ServiceParticipante.participante[] listarParticipantes() {
            ClienteSOAP.ServiceParticipante.listarParticipantesRequest inValue = new ClienteSOAP.ServiceParticipante.listarParticipantesRequest();
            ClienteSOAP.ServiceParticipante.listarParticipantesResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).listarParticipantes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarParticipantesResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.listarParticipantesAsync(ClienteSOAP.ServiceParticipante.listarParticipantesRequest request) {
            return base.Channel.listarParticipantesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.listarParticipantesResponse> listarParticipantesAsync() {
            ClienteSOAP.ServiceParticipante.listarParticipantesRequest inValue = new ClienteSOAP.ServiceParticipante.listarParticipantesRequest();
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).listarParticipantesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.filtrarParticipantePorApodo(ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest request) {
            return base.Channel.filtrarParticipantePorApodo(request);
        }
        
        public ClienteSOAP.ServiceParticipante.participante[] filtrarParticipantePorApodo(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest inValue = new ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).filtrarParticipantePorApodo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.filtrarParticipantePorApodoAsync(ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest request) {
            return base.Channel.filtrarParticipantePorApodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoResponse> filtrarParticipantePorApodoAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest inValue = new ClienteSOAP.ServiceParticipante.filtrarParticipantePorApodoRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).filtrarParticipantePorApodoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.buscarParticipanteResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.buscarParticipante(ClienteSOAP.ServiceParticipante.buscarParticipanteRequest request) {
            return base.Channel.buscarParticipante(request);
        }
        
        public ClienteSOAP.ServiceParticipante.participante buscarParticipante(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.buscarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.buscarParticipanteRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.buscarParticipanteResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).buscarParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.buscarParticipanteResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.buscarParticipanteAsync(ClienteSOAP.ServiceParticipante.buscarParticipanteRequest request) {
            return base.Channel.buscarParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.buscarParticipanteResponse> buscarParticipanteAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.buscarParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.buscarParticipanteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).buscarParticipanteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceParticipante.crearParticipanteResponse ClienteSOAP.ServiceParticipante.ServicioWebParticipante.crearParticipante(ClienteSOAP.ServiceParticipante.crearParticipanteRequest request) {
            return base.Channel.crearParticipante(request);
        }
        
        public int crearParticipante(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.crearParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.crearParticipanteRequest();
            inValue.arg0 = arg0;
            ClienteSOAP.ServiceParticipante.crearParticipanteResponse retVal = ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).crearParticipante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.crearParticipanteResponse> ClienteSOAP.ServiceParticipante.ServicioWebParticipante.crearParticipanteAsync(ClienteSOAP.ServiceParticipante.crearParticipanteRequest request) {
            return base.Channel.crearParticipanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceParticipante.crearParticipanteResponse> crearParticipanteAsync(ClienteSOAP.ServiceParticipante.participante arg0) {
            ClienteSOAP.ServiceParticipante.crearParticipanteRequest inValue = new ClienteSOAP.ServiceParticipante.crearParticipanteRequest();
            inValue.arg0 = arg0;
            return ((ClienteSOAP.ServiceParticipante.ServicioWebParticipante)(this)).crearParticipanteAsync(inValue);
        }
    }
}
